{ config, pkgs, ... }:

{
  # Theme packages installation
  # Ensures icon and cursor themes are installed system-wide
  # GTK theme is auto-generated by Stylix (no package needed)
  # Packages are defined in hyprflake.themes.* and hyprflake.cursor.* options

  environment.systemPackages = [
    # Icon theme from options (Stylix doesn't handle icons)
    config.hyprflake.style.icon.package

    # Cursor theme from options (also in Stylix, but ensure package is installed)
    config.hyprflake.style.cursor.package

    # Additional theme-related packages for compatibility
    pkgs.gtk-engine-murrine # Required by many GTK themes
    pkgs.gnome-themes-extra # Adwaita and other base themes
  ];
}

