{ config, lib, pkgs, ... }:

{
  # GTK and cursor theme configuration
  # Inherits theme settings from hyprflake.themes.* options
  # Follows Hyprland wiki recommendations for theme compatibility

  home-manager.sharedModules = [
    (_: {
      # Pointer cursor is handled by Stylix via stylix.cursor configuration
      # Stylix automatically sets home.pointerCursor with proper compatibility options
      # No need to duplicate here

      # GTK configuration
      gtk = {
        enable = true;

        # GTK theme is auto-generated by Stylix from base16 color scheme
        # No manual theme configuration needed

        # Icon theme from hyprflake.themes.icon options
        # Stylix doesn't auto-theme icons, so we configure manually
        iconTheme = {
          package = config.hyprflake.themes.icon.package;
          name = config.hyprflake.themes.icon.name;
        };

        # Font is auto-configured by Stylix
        # No manual font configuration needed
      };
    })
  ];
}

